FROM alpine:3.11.5

ENV NGINX_VERSION 1.16

RUN apk add --no-cache nginx-${NGINX_VERSION} && mkdir -p /run/nginx

EXPOSE 80

COPY custom.conf /etc/nginx/conf.d/
COPY . /opt/

CMD ["nginx", "-g", "daemon off;"]
